# Site
title: Tech Versus Me
bio: "We provide detailed comparisons between tech products and services, that enable our readers to make informed choices."
description: "We provide detailed comparisons between tech products and services, that enable our readers to make informed choices."
locale: en_US
encoding: utf-8
timezone: Asia/Kolkata
url: "https://tvm.nirantak.com"
baseurl: ""

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /:categories/:title/
      layout: post
      description: We provide detailed comparisons between tech products and services, that enable our readers to make informed choices.
      keywords: Tech Versus Me, tech, blog, tech vs me, Tech-vs-Me, tech comparison, compare
      author: Nirantak Raghav

# Jekyll
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed

# Social
analytics-id: UA-105821168-2
twitter: NirantakRaghav
github: nirantak

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/all/page:num/"

jekyll-mentions:
  base_url: https://github.com

include: [_redirects, _headers]
exclude:
  [
    README.md,
    Gemfile,
    Gemfile.lock,
    node_modules,
    gulpfile.js,
    package.json,
    package-lock.json,
    _site,
    src,
    vendor,
    CNAME,
    .env,
    netlify.toml,
    LICENSE,
    Rakefile,
    old,
  ]
